name: Build and Release Mod JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'  # Required for Minecraft 1.20.5+ and snapshots
        distribution: 'temurin'

    - name: Grant Execute Permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build  # Replaces mvn command

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mod-jar
        path: build/libs/*.jar

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only on push to main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}-snapshot
        release_name: Snapshot Release ${{ github.run_number }}
        draft: false
        prerelease: true  # Suitable for snapshot mods

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/yourmod-1.0.0-snapshot.jar  # Replace with your .jar name
        asset_name: yourmod-1.0.0-snapshot.jar
        asset_content_type: application/java-archive
